image: registry.cn-hangzhou.aliyuncs.com/choerodon-tools/cibase:0.8.1

stages:
  - build
  - release

variables:
  GIT_SUBMODULE_STRATEGY: recursive

build:
  stage: build
  script:
    - node_module_ci
    - node_build build
    - cp -r Dockerfile $CI_PROJECT_DIR/docker
    - cp -r dist $CI_PROJECT_DIR/docker/dist
    - cp -r node_modules/choerodon-front-boot/structure $CI_PROJECT_DIR/docker/structure
    - cp -r parent-structure $CI_PROJECT_DIR/docker/parent-structure
    - cd $CI_PROJECT_DIR
    - kaniko -c $CI_PROJECT_DIR/docker -f $CI_PROJECT_DIR/docker/Dockerfile -d ${DOCKER_REGISTRY}/${GROUP_NAME}/${PROJECT_NAME}:${CI_COMMIT_TAG}

release:
  stage: release
  script:
    - chart_build


.auto_devops: &auto_devops |
  http_status_code=`curl -o .auto_devops.sh -s -m 10 --connect-timeout 10 -w %{http_code} "${CHOERODON_URL}/devops/ci?token=${Token}&type=front"`
  if [ "$http_status_code" != "200" ]; then
    cat .auto_devops.sh
    exit 1
  fi
  source .auto_devops.sh

  function echo_time(){
    while true
    do
        sleep 30
        date "+%Y-%m-%d %H:%M:%S"
    done
  }

  function node_module_ci() {
    npm i --registry https://nexus.choerodon.com.cn/repository/choerodon-npm/ --sass-binary-site=http://npm.taobao.org/mirrors/node-sass
    mkdir -p $CI_PROJECT_DIR/docker
    mkdir -p ./tmp/
    cp -r ./node_modules/choerodon-front-boot/structure ./tmp/structure
    modules=(iam devops agile testManager wiki issue apim)
    folers=(choerodon-front-iam choerodon-front-devops choerodon-front-agile choerodon-front-test-manager choerodon-front-wiki choerodon-front-issue choerodon-front-apim)
    for i in "${!modules[@]}"; 
    do 
      mkdir -p ./tmp/${modules[$i]}/src/app/${modules[$i]}/
      cp -r ./${folers[$i]}/${modules[$i]}/src/app/${modules[$i]}/config ./tmp/${modules[$i]}/src/app/${modules[$i]}/
    done
    cd ./tmp
    python ./structure/menu/__init__.py -o yml -m ${modules[@]}
    python ./structure/dashboard/__init__.py -o yml -m iam devops agile testManager wiki
    cp -r menu.yml $CI_PROJECT_DIR/docker
    cp -r dashboard.yml $CI_PROJECT_DIR/docker
    rm -rf ./tmp
    cd ..
  }

  function node_build() {
    echo_time &
    chmod -R 777 node_modules
    modules=(choerodon-front-iam/iam choerodon-front-devops/devops choerodon-front-agile/agile choerodon-front-test-manager/testManager choerodon-front-wiki/wiki choerodon-front-issue/issue choerodon-front-apim/apim)
    npm run ${1:-"build"} ${modules[@]} -registry https://nexus.choerodon.com.cn/repository/choerodon-npm/
    find dist -name '*.js' | xargs sed -i "s/localhost:version/$CI_COMMIT_TAG/g"
    ps -ex | grep sleep | grep -v grep | awk '{print $1}' | xargs kill -9
  }

  function docker_build(){
    kaniko -c $CI_PROJECT_DIR -f $CI_PROJECT_DIR/docker/Dockerfile -d ${DOCKER_REGISTRY}/${GROUP_NAME}/${PROJECT_NAME}:${CI_COMMIT_TAG}
  }

before_script:
  - *auto_devops